// GET CONSTANTS ALL USERS
export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

// GET CONSTANTS ALL VENDORS
export const GET_ALL_VENDORS_REQUEST = "GET_ALL_VENDORS_REQUEST";
export const GET_ALL_VENDORS_SUCCESS = "GET_ALL_VENDORS_SUCCESS";
export const GET_ALL_VENDORS_FAIL = "GET_ALL_VENDORS_FAIL";