// MAIN SEARCH CONSTANTS
export const MAIN_SEARCH_REQUEST = "MAIN_SEARCH_REQUEST";
export const MAIN_SEARCH_SUCCESS = "MAIN_SEARCH_SUCCESS";
export const MAIN_SEARCH_FAIL = "MAIN_SEARCH_FAIL";

// TIFFIN DETAILS CONSTANTS
export const TIFFIN_DETAILS_FETCH_REQUEST = "TIFFIN_DETAILS_FETCH_REQUEST";
export const TIFFIN_DETAILS_FETCH_SUCCESS = "TIFFIN_DETAILS_FETCH_SUCCESS";
export const TIFFIN_DETAILS_FETCH_FAIL = "TIFFIN_DETAILS_FETCH_FAIL";

// CHECKOUT DETAILS CONSTANTS
export const CHECKOUT_DETAILS_SUCCESS = 'CHECKOUT_DETAILS_SUCCESS';